### ISSUE TITLE
Db2 Warehouse on Cloud: Enterprise Transactional (supporting OLTP) does not exist

### ISSUE THREAD

**Issue by andrewyuau** [IBM-Bluemix-Docs/mobilefoundation#1]
As per https://console.bluemix.net/docs/services/mobilefoundation/c_using_mfs_p4.html#using_mobilefoundation_p4 - "Mobile Foundation: Professional Per Capacity is supported only with Db2 Warehouse on Cloud: Enterprise Transactional (supporting OLTP) IBM Cloud plans."

However, that plan does not exist under Db2 Warehouse on Cloud (https://console.bluemix.net/catalog/services/db2-warehouse-on-cloud). The right plan should be Db2 on Cloud: Precise Performance at https://console.bluemix.net/catalog/services/db2-on-cloud .

**Comment by sreelathasankaranarayanan** [comment]
This is fixed now, we have made changes to just say Db2 on Cloud and not call out any specific plan as per dev inputs.
