### ISSUE TITLE
Container groups are deprecated

### ISSUE THREAD

**Issue by kKronstainBrown** [IBM-Bluemix-Docs/mobilefoundation#2]
Container groups in the IBM Cloud Container Service are deprecated. These instructions need to be updated with the Kubernetes version of the service.
https://github.com/IBM-Bluemix-Docs/mobilefoundation/blob/master/c_using_mfs_p1.md
https://github.com/IBM-Bluemix-Docs/mobilefoundation/blob/master/c_using_mfs_p2.md
https://github.com/IBM-Bluemix-Docs/mobilefoundation/blob/master/c_using_mfs_p3.md
https://github.com/IBM-Bluemix-Docs/mobilefoundation/blob/master/c_using_mfs_p4.md

**Comment by sreelathasankaranarayanan** [comment]
@kKronstainBrown thanks for raising this,  I shall get this addressed.

**Comment by sreelathasankaranarayanan** [comment]
addressed. the mentioned topics does not have reference to container groups.
